version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - api
      - streamlit

  api:
    build: ./api
    expose:
      - 8000

  streamlit:
    build: ./streamlit
    expose:
      - 8501
